###
## THEME
###

# Impostazioni generali della barra di stato
# General status bar settings
set -g status-justify left
set -g status-style bg=colour235,fg=colour136

# left segment (Session name)
set -g status-left-length 30
set -g status-left "#[bg=colour190,fg=colour235,bold] #S #[bg=colour235,fg=colour190,nobold]"

# Tabs and windows format customization
set -g window-status-format "#[fg=colour244,bg=colour235] #I  #W "
set -g window-status-current-format "#[fg=colour235,bg=colour20]#[fg=colour255,bg=colour20,bold] #I  #W #[fg=colour20,bg=colour235,nobold]"

# Right segment (clock and date)
set -g status-right-length 50
set -g status-right "#[fg=colour20,bg=colour235]#[fg=colour255,bg=colour20,bold]  %H:%M #[fg=colour235,bg=colour20]#[fg=colour255,bg=colour235] %d-%m-%Y "

###
## SETTINGS
###

# enable mouse
set -g mouse on
# enable system clipboard
set -g set-clipboard on
bind-key -T copy-mode-vi y send -X copy-pipe-and-cancel "xclip -selection clipboard -in"

# enable vim-mode keymapping
set -g mode-keys vi

# enable colors
set -g default-terminal "tmux-256color"
set -ag terminal-overrides ",xterm-256color:Cc"

# Prefix
set -g prefix M-Space
unbind C-b
bind M-Space send-prefix


# Pane navigation
bind Left  select-pane -L
bind Down  select-pane -D
bind Up    select-pane -U
bind Right select-pane -R

# Pane resizing
bind -n M-S-Left  resize-pane -L 5
bind -n M-S-Down  resize-pane -D 5
bind -n M-S-Up    resize-pane -U 5
bind -n M-S-Right resize-pane -R 5

# Pane splitting
bind M-h split-window -v
bind M-v split-window -h

# new tab
bind t new-window 

# Show time
bind M-t clock-mode

# new session
bind c new-session
